<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Events/DiadocMessage-PostApi.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Events;

/**
 * Protobuf message :
 * AgentSIB.Diadoc.Api.Proto.Events.EncryptedInvoiceCorrectionMetadata
 */
class EncryptedInvoiceCorrectionMetadata extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * OriginalInvoiceDateAndNumber required message = 1
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber
     */
    protected $OriginalInvoiceDateAndNumber = null;

    /**
     * OriginalInvoiceRevisionDateAndNumber optional message = 2
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber
     */
    protected $OriginalInvoiceRevisionDateAndNumber = null;

    /**
     * InvoiceCorrectionRevisionDateAndNumber optional message = 3
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber
     */
    protected $InvoiceCorrectionRevisionDateAndNumber = null;

    /**
     * Check if 'OriginalInvoiceDateAndNumber' has a value
     *
     * @return bool
     */
    public function hasOriginalInvoiceDateAndNumber()
    {
        return $this->OriginalInvoiceDateAndNumber !== null;
    }

    /**
     * Get 'OriginalInvoiceDateAndNumber' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber
     */
    public function getOriginalInvoiceDateAndNumber()
    {
        return $this->OriginalInvoiceDateAndNumber;
    }

    /**
     * Set 'OriginalInvoiceDateAndNumber' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $value
     */
    public function setOriginalInvoiceDateAndNumber(\AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $value)
    {
        $this->OriginalInvoiceDateAndNumber = $value;
    }

    /**
     * Check if 'OriginalInvoiceRevisionDateAndNumber' has a value
     *
     * @return bool
     */
    public function hasOriginalInvoiceRevisionDateAndNumber()
    {
        return $this->OriginalInvoiceRevisionDateAndNumber !== null;
    }

    /**
     * Get 'OriginalInvoiceRevisionDateAndNumber' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber
     */
    public function getOriginalInvoiceRevisionDateAndNumber()
    {
        return $this->OriginalInvoiceRevisionDateAndNumber;
    }

    /**
     * Set 'OriginalInvoiceRevisionDateAndNumber' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $value
     */
    public function setOriginalInvoiceRevisionDateAndNumber(\AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $value = null)
    {
        $this->OriginalInvoiceRevisionDateAndNumber = $value;
    }

    /**
     * Check if 'InvoiceCorrectionRevisionDateAndNumber' has a value
     *
     * @return bool
     */
    public function hasInvoiceCorrectionRevisionDateAndNumber()
    {
        return $this->InvoiceCorrectionRevisionDateAndNumber !== null;
    }

    /**
     * Get 'InvoiceCorrectionRevisionDateAndNumber' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber
     */
    public function getInvoiceCorrectionRevisionDateAndNumber()
    {
        return $this->InvoiceCorrectionRevisionDateAndNumber;
    }

    /**
     * Set 'InvoiceCorrectionRevisionDateAndNumber' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $value
     */
    public function setInvoiceCorrectionRevisionDateAndNumber(\AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $value = null)
    {
        $this->InvoiceCorrectionRevisionDateAndNumber = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['OriginalInvoiceDateAndNumber'])) {
            throw new \InvalidArgumentException('Field "OriginalInvoiceDateAndNumber" (tag 1) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'OriginalInvoiceRevisionDateAndNumber' => null,
            'InvoiceCorrectionRevisionDateAndNumber' => null
        ], $values);

        $message->setOriginalInvoiceDateAndNumber($values['OriginalInvoiceDateAndNumber']);
        $message->setOriginalInvoiceRevisionDateAndNumber($values['OriginalInvoiceRevisionDateAndNumber']);
        $message->setInvoiceCorrectionRevisionDateAndNumber($values['InvoiceCorrectionRevisionDateAndNumber']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'EncryptedInvoiceCorrectionMetadata',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'OriginalInvoiceDateAndNumber',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Docflow.DocumentDateAndNumber'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'OriginalInvoiceRevisionDateAndNumber',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Docflow.DocumentDateAndNumber'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'InvoiceCorrectionRevisionDateAndNumber',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Docflow.DocumentDateAndNumber'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->OriginalInvoiceDateAndNumber === null) {
            throw new \UnexpectedValueException('Field "\\AgentSIB\\Diadoc\\Api\\Proto\\Events\\EncryptedInvoiceCorrectionMetadata#OriginalInvoiceDateAndNumber" (tag 1) is required but has no value.');
        }

        if ($this->OriginalInvoiceDateAndNumber !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeVarint($stream, $this->OriginalInvoiceDateAndNumber->serializedSize($sizeContext));
            $this->OriginalInvoiceDateAndNumber->writeTo($context);
        }

        if ($this->OriginalInvoiceRevisionDateAndNumber !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeVarint($stream, $this->OriginalInvoiceRevisionDateAndNumber->serializedSize($sizeContext));
            $this->OriginalInvoiceRevisionDateAndNumber->writeTo($context);
        }

        if ($this->InvoiceCorrectionRevisionDateAndNumber !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeVarint($stream, $this->InvoiceCorrectionRevisionDateAndNumber->serializedSize($sizeContext));
            $this->InvoiceCorrectionRevisionDateAndNumber->writeTo($context);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber();

                $this->OriginalInvoiceDateAndNumber = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber();

                $this->OriginalInvoiceRevisionDateAndNumber = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentDateAndNumber();

                $this->InvoiceCorrectionRevisionDateAndNumber = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->OriginalInvoiceDateAndNumber !== null) {
            $innerSize = $this->OriginalInvoiceDateAndNumber->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->OriginalInvoiceRevisionDateAndNumber !== null) {
            $innerSize = $this->OriginalInvoiceRevisionDateAndNumber->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->InvoiceCorrectionRevisionDateAndNumber !== null) {
            $innerSize = $this->InvoiceCorrectionRevisionDateAndNumber->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->OriginalInvoiceDateAndNumber = null;
        $this->OriginalInvoiceRevisionDateAndNumber = null;
        $this->InvoiceCorrectionRevisionDateAndNumber = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AgentSIB\Diadoc\Api\Proto\Events\EncryptedInvoiceCorrectionMetadata) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->OriginalInvoiceDateAndNumber = ($message->OriginalInvoiceDateAndNumber !== null) ? $message->OriginalInvoiceDateAndNumber : $this->OriginalInvoiceDateAndNumber;
        $this->OriginalInvoiceRevisionDateAndNumber = ($message->OriginalInvoiceRevisionDateAndNumber !== null) ? $message->OriginalInvoiceRevisionDateAndNumber : $this->OriginalInvoiceRevisionDateAndNumber;
        $this->InvoiceCorrectionRevisionDateAndNumber = ($message->InvoiceCorrectionRevisionDateAndNumber !== null) ? $message->InvoiceCorrectionRevisionDateAndNumber : $this->InvoiceCorrectionRevisionDateAndNumber;
    }


}

