<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Recognition/Recognition.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Recognition;

/**
 * Protobuf message : AgentSIB.Diadoc.Api.Proto.Recognition.Recognized
 */
class Recognized extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * RecognitionId required string = 1
     *
     * @var string
     */
    protected $RecognitionId = null;

    /**
     * ErrorMessage optional string = 2
     *
     * @var string
     */
    protected $ErrorMessage = null;

    /**
     * FileName optional string = 3
     *
     * @var string
     */
    protected $FileName = null;

    /**
     * DocumentType optional enum = 4
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedDocumentType
     */
    protected $DocumentType = null;

    /**
     * Content optional bytes = 5
     *
     * @var \Protobuf\Stream
     */
    protected $Content = null;

    /**
     * Invoice optional message = 6
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedInvoice
     */
    protected $Invoice = null;

    /**
     * {@inheritdoc}
     */
    public function __construct($stream = null, \Protobuf\Configuration $configuration = null)
    {
        $this->DocumentType = \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedDocumentType::UnknownRecognizedDocumentType();

        parent::__construct($stream, $configuration);
    }

    /**
     * Check if 'RecognitionId' has a value
     *
     * @return bool
     */
    public function hasRecognitionId()
    {
        return $this->RecognitionId !== null;
    }

    /**
     * Get 'RecognitionId' value
     *
     * @return string
     */
    public function getRecognitionId()
    {
        return $this->RecognitionId;
    }

    /**
     * Set 'RecognitionId' value
     *
     * @param string $value
     */
    public function setRecognitionId($value)
    {
        $this->RecognitionId = $value;
    }

    /**
     * Check if 'ErrorMessage' has a value
     *
     * @return bool
     */
    public function hasErrorMessage()
    {
        return $this->ErrorMessage !== null;
    }

    /**
     * Get 'ErrorMessage' value
     *
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->ErrorMessage;
    }

    /**
     * Set 'ErrorMessage' value
     *
     * @param string $value
     */
    public function setErrorMessage($value = null)
    {
        $this->ErrorMessage = $value;
    }

    /**
     * Check if 'FileName' has a value
     *
     * @return bool
     */
    public function hasFileName()
    {
        return $this->FileName !== null;
    }

    /**
     * Get 'FileName' value
     *
     * @return string
     */
    public function getFileName()
    {
        return $this->FileName;
    }

    /**
     * Set 'FileName' value
     *
     * @param string $value
     */
    public function setFileName($value = null)
    {
        $this->FileName = $value;
    }

    /**
     * Check if 'DocumentType' has a value
     *
     * @return bool
     */
    public function hasDocumentType()
    {
        return $this->DocumentType !== null;
    }

    /**
     * Get 'DocumentType' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedDocumentType
     */
    public function getDocumentType()
    {
        return $this->DocumentType;
    }

    /**
     * Set 'DocumentType' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedDocumentType $value
     */
    public function setDocumentType(\AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedDocumentType $value = null)
    {
        $this->DocumentType = $value;
    }

    /**
     * Check if 'Content' has a value
     *
     * @return bool
     */
    public function hasContent()
    {
        return $this->Content !== null;
    }

    /**
     * Get 'Content' value
     *
     * @return \Protobuf\Stream
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * Set 'Content' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setContent($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->Content = $value;
    }

    /**
     * Check if 'Invoice' has a value
     *
     * @return bool
     */
    public function hasInvoice()
    {
        return $this->Invoice !== null;
    }

    /**
     * Get 'Invoice' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedInvoice
     */
    public function getInvoice()
    {
        return $this->Invoice;
    }

    /**
     * Set 'Invoice' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedInvoice $value
     */
    public function setInvoice(\AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedInvoice $value = null)
    {
        $this->Invoice = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['RecognitionId'])) {
            throw new \InvalidArgumentException('Field "RecognitionId" (tag 1) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'ErrorMessage' => null,
            'FileName' => null,
            'DocumentType' => \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedDocumentType::UnknownRecognizedDocumentType(),
            'Content' => null,
            'Invoice' => null
        ], $values);

        $message->setRecognitionId($values['RecognitionId']);
        $message->setErrorMessage($values['ErrorMessage']);
        $message->setFileName($values['FileName']);
        $message->setDocumentType($values['DocumentType']);
        $message->setContent($values['Content']);
        $message->setInvoice($values['Invoice']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'Recognized',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'RecognitionId',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'ErrorMessage',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'FileName',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'DocumentType',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Recognition.RecognizedDocumentType',
                    'default_value' => \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedDocumentType::UnknownRecognizedDocumentType()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'Content',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'Invoice',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Recognition.RecognizedInvoice'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->RecognitionId === null) {
            throw new \UnexpectedValueException('Field "\\AgentSIB\\Diadoc\\Api\\Proto\\Recognition\\Recognized#RecognitionId" (tag 1) is required but has no value.');
        }

        if ($this->RecognitionId !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->RecognitionId);
        }

        if ($this->ErrorMessage !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->ErrorMessage);
        }

        if ($this->FileName !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeString($stream, $this->FileName);
        }

        if ($this->DocumentType !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->DocumentType->value());
        }

        if ($this->Content !== null) {
            $writer->writeVarint($stream, 42);
            $writer->writeByteStream($stream, $this->Content);
        }

        if ($this->Invoice !== null) {
            $writer->writeVarint($stream, 50);
            $writer->writeVarint($stream, $this->Invoice->serializedSize($sizeContext));
            $this->Invoice->writeTo($context);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->RecognitionId = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->ErrorMessage = $reader->readString($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->FileName = $reader->readString($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->DocumentType = \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedDocumentType::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->Content = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedInvoice();

                $this->Invoice = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->RecognitionId !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->RecognitionId);
        }

        if ($this->ErrorMessage !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->ErrorMessage);
        }

        if ($this->FileName !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->FileName);
        }

        if ($this->DocumentType !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->DocumentType->value());
        }

        if ($this->Content !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->Content);
        }

        if ($this->Invoice !== null) {
            $innerSize = $this->Invoice->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->RecognitionId = null;
        $this->ErrorMessage = null;
        $this->FileName = null;
        $this->DocumentType = \AgentSIB\Diadoc\Api\Proto\Recognition\RecognizedDocumentType::UnknownRecognizedDocumentType();
        $this->Content = null;
        $this->Invoice = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AgentSIB\Diadoc\Api\Proto\Recognition\Recognized) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->RecognitionId = ($message->RecognitionId !== null) ? $message->RecognitionId : $this->RecognitionId;
        $this->ErrorMessage = ($message->ErrorMessage !== null) ? $message->ErrorMessage : $this->ErrorMessage;
        $this->FileName = ($message->FileName !== null) ? $message->FileName : $this->FileName;
        $this->DocumentType = ($message->DocumentType !== null) ? $message->DocumentType : $this->DocumentType;
        $this->Content = ($message->Content !== null) ? $message->Content : $this->Content;
        $this->Invoice = ($message->Invoice !== null) ? $message->Invoice : $this->Invoice;
    }


}

