<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Dss/DssSign.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Dss;

/**
 * Protobuf message : AgentSIB.Diadoc.Api.Proto.Dss.DssSignResult
 */
class DssSignResult extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * OperationStatus optional enum = 1
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Dss\DssOperationStatus
     */
    protected $OperationStatus = null;

    /**
     * FileSigningResults repeated message = 2
     *
     * @var \Protobuf\Collection<\AgentSIB\Diadoc\Api\Proto\Dss\DssFileSigningResult>
     */
    protected $FileSigningResults = null;

    /**
     * {@inheritdoc}
     */
    public function __construct($stream = null, \Protobuf\Configuration $configuration = null)
    {
        $this->OperationStatus = \AgentSIB\Diadoc\Api\Proto\Dss\DssOperationStatus::Unknown();

        parent::__construct($stream, $configuration);
    }

    /**
     * Check if 'OperationStatus' has a value
     *
     * @return bool
     */
    public function hasOperationStatus()
    {
        return $this->OperationStatus !== null;
    }

    /**
     * Get 'OperationStatus' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Dss\DssOperationStatus
     */
    public function getOperationStatus()
    {
        return $this->OperationStatus;
    }

    /**
     * Set 'OperationStatus' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Dss\DssOperationStatus $value
     */
    public function setOperationStatus(\AgentSIB\Diadoc\Api\Proto\Dss\DssOperationStatus $value = null)
    {
        $this->OperationStatus = $value;
    }

    /**
     * Check if 'FileSigningResults' has a value
     *
     * @return bool
     */
    public function hasFileSigningResultsList()
    {
        return $this->FileSigningResults !== null;
    }

    /**
     * Get 'FileSigningResults' value
     *
     * @return \Protobuf\Collection<\AgentSIB\Diadoc\Api\Proto\Dss\DssFileSigningResult>
     */
    public function getFileSigningResultsList()
    {
        return $this->FileSigningResults;
    }

    /**
     * Set 'FileSigningResults' value
     *
     * @param \Protobuf\Collection<\AgentSIB\Diadoc\Api\Proto\Dss\DssFileSigningResult> $value
     */
    public function setFileSigningResultsList(\Protobuf\Collection $value = null)
    {
        $this->FileSigningResults = $value;
    }

    /**
     * Add a new element to 'FileSigningResults'
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Dss\DssFileSigningResult $value
     */
    public function addFileSigningResults(\AgentSIB\Diadoc\Api\Proto\Dss\DssFileSigningResult $value)
    {
        if ($this->FileSigningResults === null) {
            $this->FileSigningResults = new \Protobuf\MessageCollection();
        }

        $this->FileSigningResults->add($value);
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'OperationStatus' => \AgentSIB\Diadoc\Api\Proto\Dss\DssOperationStatus::Unknown(),
            'FileSigningResults' => []
        ], $values);

        $message->setOperationStatus($values['OperationStatus']);

        foreach ($values['FileSigningResults'] as $item) {
            $message->addFileSigningResults($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'DssSignResult',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'OperationStatus',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Dss.DssOperationStatus',
                    'default_value' => \AgentSIB\Diadoc\Api\Proto\Dss\DssOperationStatus::Unknown()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'FileSigningResults',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Dss.DssFileSigningResult'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->OperationStatus !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->OperationStatus->value());
        }

        if ($this->FileSigningResults !== null) {
            foreach ($this->FileSigningResults as $val) {
                $writer->writeVarint($stream, 18);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->OperationStatus = \AgentSIB\Diadoc\Api\Proto\Dss\DssOperationStatus::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Dss\DssFileSigningResult();

                if ($this->FileSigningResults === null) {
                    $this->FileSigningResults = new \Protobuf\MessageCollection();
                }

                $this->FileSigningResults->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->OperationStatus !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->OperationStatus->value());
        }

        if ($this->FileSigningResults !== null) {
            foreach ($this->FileSigningResults as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->OperationStatus = \AgentSIB\Diadoc\Api\Proto\Dss\DssOperationStatus::Unknown();
        $this->FileSigningResults = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AgentSIB\Diadoc\Api\Proto\Dss\DssSignResult) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->OperationStatus = ($message->OperationStatus !== null) ? $message->OperationStatus : $this->OperationStatus;
        $this->FileSigningResults = ($message->FileSigningResults !== null) ? $message->FileSigningResults : $this->FileSigningResults;
    }


}

