<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Docflow/DocumentInfoV3.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Docflow;

/**
 * Protobuf message : AgentSIB.Diadoc.Api.Proto.Docflow.DocumentTemplateInfo
 */
class DocumentTemplateInfo extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * LetterParticipants required message = 1
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentParticipants
     */
    protected $LetterParticipants = null;

    /**
     * TransformedToLetterIds repeated string = 2
     *
     * @var \Protobuf\Collection
     */
    protected $TransformedToLetterIds = null;

    /**
     * TemplateTransformationInfos repeated message = 3
     *
     * @var \Protobuf\Collection<\AgentSIB\Diadoc\Api\Proto\Docflow\TemplateTransformationInfo>
     */
    protected $TemplateTransformationInfos = null;

    /**
     * TemplateRefusalInfo optional message = 4
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Docflow\TemplateRefusalInfo
     */
    protected $TemplateRefusalInfo = null;

    /**
     * Check if 'LetterParticipants' has a value
     *
     * @return bool
     */
    public function hasLetterParticipants()
    {
        return $this->LetterParticipants !== null;
    }

    /**
     * Get 'LetterParticipants' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentParticipants
     */
    public function getLetterParticipants()
    {
        return $this->LetterParticipants;
    }

    /**
     * Set 'LetterParticipants' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentParticipants $value
     */
    public function setLetterParticipants(\AgentSIB\Diadoc\Api\Proto\Docflow\DocumentParticipants $value)
    {
        $this->LetterParticipants = $value;
    }

    /**
     * Check if 'TransformedToLetterIds' has a value
     *
     * @return bool
     */
    public function hasTransformedToLetterIdsList()
    {
        return $this->TransformedToLetterIds !== null;
    }

    /**
     * Get 'TransformedToLetterIds' value
     *
     * @return \Protobuf\Collection
     */
    public function getTransformedToLetterIdsList()
    {
        return $this->TransformedToLetterIds;
    }

    /**
     * Set 'TransformedToLetterIds' value
     *
     * @param \Protobuf\Collection $value
     */
    public function setTransformedToLetterIdsList(\Protobuf\Collection $value = null)
    {
        $this->TransformedToLetterIds = $value;
    }

    /**
     * Add a new element to 'TransformedToLetterIds'
     *
     * @param string $value
     */
    public function addTransformedToLetterIds($value)
    {
        if ($this->TransformedToLetterIds === null) {
            $this->TransformedToLetterIds = new \Protobuf\ScalarCollection();
        }

        $this->TransformedToLetterIds->add($value);
    }

    /**
     * Check if 'TemplateTransformationInfos' has a value
     *
     * @return bool
     */
    public function hasTemplateTransformationInfosList()
    {
        return $this->TemplateTransformationInfos !== null;
    }

    /**
     * Get 'TemplateTransformationInfos' value
     *
     * @return \Protobuf\Collection<\AgentSIB\Diadoc\Api\Proto\Docflow\TemplateTransformationInfo>
     */
    public function getTemplateTransformationInfosList()
    {
        return $this->TemplateTransformationInfos;
    }

    /**
     * Set 'TemplateTransformationInfos' value
     *
     * @param \Protobuf\Collection<\AgentSIB\Diadoc\Api\Proto\Docflow\TemplateTransformationInfo> $value
     */
    public function setTemplateTransformationInfosList(\Protobuf\Collection $value = null)
    {
        $this->TemplateTransformationInfos = $value;
    }

    /**
     * Add a new element to 'TemplateTransformationInfos'
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Docflow\TemplateTransformationInfo $value
     */
    public function addTemplateTransformationInfos(\AgentSIB\Diadoc\Api\Proto\Docflow\TemplateTransformationInfo $value)
    {
        if ($this->TemplateTransformationInfos === null) {
            $this->TemplateTransformationInfos = new \Protobuf\MessageCollection();
        }

        $this->TemplateTransformationInfos->add($value);
    }

    /**
     * Check if 'TemplateRefusalInfo' has a value
     *
     * @return bool
     */
    public function hasTemplateRefusalInfo()
    {
        return $this->TemplateRefusalInfo !== null;
    }

    /**
     * Get 'TemplateRefusalInfo' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Docflow\TemplateRefusalInfo
     */
    public function getTemplateRefusalInfo()
    {
        return $this->TemplateRefusalInfo;
    }

    /**
     * Set 'TemplateRefusalInfo' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Docflow\TemplateRefusalInfo $value
     */
    public function setTemplateRefusalInfo(\AgentSIB\Diadoc\Api\Proto\Docflow\TemplateRefusalInfo $value = null)
    {
        $this->TemplateRefusalInfo = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['LetterParticipants'])) {
            throw new \InvalidArgumentException('Field "LetterParticipants" (tag 1) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'TransformedToLetterIds' => [],
            'TemplateTransformationInfos' => [],
            'TemplateRefusalInfo' => null
        ], $values);

        $message->setLetterParticipants($values['LetterParticipants']);
        $message->setTemplateRefusalInfo($values['TemplateRefusalInfo']);

        foreach ($values['TransformedToLetterIds'] as $item) {
            $message->addTransformedToLetterIds($item);
        }

        foreach ($values['TemplateTransformationInfos'] as $item) {
            $message->addTemplateTransformationInfos($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'DocumentTemplateInfo',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'LetterParticipants',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Docflow.DocumentParticipants'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'TransformedToLetterIds',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'TemplateTransformationInfos',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Docflow.TemplateTransformationInfo'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'TemplateRefusalInfo',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Docflow.TemplateRefusalInfo'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->LetterParticipants === null) {
            throw new \UnexpectedValueException('Field "\\AgentSIB\\Diadoc\\Api\\Proto\\Docflow\\DocumentTemplateInfo#LetterParticipants" (tag 1) is required but has no value.');
        }

        if ($this->LetterParticipants !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeVarint($stream, $this->LetterParticipants->serializedSize($sizeContext));
            $this->LetterParticipants->writeTo($context);
        }

        if ($this->TransformedToLetterIds !== null) {
            foreach ($this->TransformedToLetterIds as $val) {
                $writer->writeVarint($stream, 18);
                $writer->writeString($stream, $val);
            }
        }

        if ($this->TemplateTransformationInfos !== null) {
            foreach ($this->TemplateTransformationInfos as $val) {
                $writer->writeVarint($stream, 26);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->TemplateRefusalInfo !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeVarint($stream, $this->TemplateRefusalInfo->serializedSize($sizeContext));
            $this->TemplateRefusalInfo->writeTo($context);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentParticipants();

                $this->LetterParticipants = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                if ($this->TransformedToLetterIds === null) {
                    $this->TransformedToLetterIds = new \Protobuf\ScalarCollection();
                }

                $this->TransformedToLetterIds->add($reader->readString($stream));

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Docflow\TemplateTransformationInfo();

                if ($this->TemplateTransformationInfos === null) {
                    $this->TemplateTransformationInfos = new \Protobuf\MessageCollection();
                }

                $this->TemplateTransformationInfos->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Docflow\TemplateRefusalInfo();

                $this->TemplateRefusalInfo = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->LetterParticipants !== null) {
            $innerSize = $this->LetterParticipants->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->TransformedToLetterIds !== null) {
            foreach ($this->TransformedToLetterIds as $val) {
                $size += 1;
                $size += $calculator->computeStringSize($val);
            }
        }

        if ($this->TemplateTransformationInfos !== null) {
            foreach ($this->TemplateTransformationInfos as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->TemplateRefusalInfo !== null) {
            $innerSize = $this->TemplateRefusalInfo->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->LetterParticipants = null;
        $this->TransformedToLetterIds = null;
        $this->TemplateTransformationInfos = null;
        $this->TemplateRefusalInfo = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AgentSIB\Diadoc\Api\Proto\Docflow\DocumentTemplateInfo) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->LetterParticipants = ($message->LetterParticipants !== null) ? $message->LetterParticipants : $this->LetterParticipants;
        $this->TransformedToLetterIds = ($message->TransformedToLetterIds !== null) ? $message->TransformedToLetterIds : $this->TransformedToLetterIds;
        $this->TemplateTransformationInfos = ($message->TemplateTransformationInfos !== null) ? $message->TemplateTransformationInfos : $this->TemplateTransformationInfos;
        $this->TemplateRefusalInfo = ($message->TemplateRefusalInfo !== null) ? $message->TemplateRefusalInfo : $this->TemplateRefusalInfo;
    }


}

