<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Employees/EmployeeToUpdate.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Employees;

/**
 * Protobuf message : AgentSIB.Diadoc.Api.Proto.Employees.EmployeeToUpdate
 */
class EmployeeToUpdate extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * Permissions optional message = 1
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Employees\EmployeePermissionsPatch
     */
    protected $Permissions = null;

    /**
     * Position optional message = 2
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Employees\EmployeePositionPatch
     */
    protected $Position = null;

    /**
     * CanBeInvitedForChat optional message = 3
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Employees\EmployeeCanBeInvitedForChatPatch
     */
    protected $CanBeInvitedForChat = null;

    /**
     * Check if 'Permissions' has a value
     *
     * @return bool
     */
    public function hasPermissions()
    {
        return $this->Permissions !== null;
    }

    /**
     * Get 'Permissions' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Employees\EmployeePermissionsPatch
     */
    public function getPermissions()
    {
        return $this->Permissions;
    }

    /**
     * Set 'Permissions' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Employees\EmployeePermissionsPatch $value
     */
    public function setPermissions(\AgentSIB\Diadoc\Api\Proto\Employees\EmployeePermissionsPatch $value = null)
    {
        $this->Permissions = $value;
    }

    /**
     * Check if 'Position' has a value
     *
     * @return bool
     */
    public function hasPosition()
    {
        return $this->Position !== null;
    }

    /**
     * Get 'Position' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Employees\EmployeePositionPatch
     */
    public function getPosition()
    {
        return $this->Position;
    }

    /**
     * Set 'Position' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Employees\EmployeePositionPatch $value
     */
    public function setPosition(\AgentSIB\Diadoc\Api\Proto\Employees\EmployeePositionPatch $value = null)
    {
        $this->Position = $value;
    }

    /**
     * Check if 'CanBeInvitedForChat' has a value
     *
     * @return bool
     */
    public function hasCanBeInvitedForChat()
    {
        return $this->CanBeInvitedForChat !== null;
    }

    /**
     * Get 'CanBeInvitedForChat' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Employees\EmployeeCanBeInvitedForChatPatch
     */
    public function getCanBeInvitedForChat()
    {
        return $this->CanBeInvitedForChat;
    }

    /**
     * Set 'CanBeInvitedForChat' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Employees\EmployeeCanBeInvitedForChatPatch $value
     */
    public function setCanBeInvitedForChat(\AgentSIB\Diadoc\Api\Proto\Employees\EmployeeCanBeInvitedForChatPatch $value = null)
    {
        $this->CanBeInvitedForChat = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'Permissions' => null,
            'Position' => null,
            'CanBeInvitedForChat' => null
        ], $values);

        $message->setPermissions($values['Permissions']);
        $message->setPosition($values['Position']);
        $message->setCanBeInvitedForChat($values['CanBeInvitedForChat']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'EmployeeToUpdate',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'Permissions',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Employees.EmployeePermissionsPatch'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'Position',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Employees.EmployeePositionPatch'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'CanBeInvitedForChat',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Employees.EmployeeCanBeInvitedForChatPatch'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->Permissions !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeVarint($stream, $this->Permissions->serializedSize($sizeContext));
            $this->Permissions->writeTo($context);
        }

        if ($this->Position !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeVarint($stream, $this->Position->serializedSize($sizeContext));
            $this->Position->writeTo($context);
        }

        if ($this->CanBeInvitedForChat !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeVarint($stream, $this->CanBeInvitedForChat->serializedSize($sizeContext));
            $this->CanBeInvitedForChat->writeTo($context);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Employees\EmployeePermissionsPatch();

                $this->Permissions = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Employees\EmployeePositionPatch();

                $this->Position = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Employees\EmployeeCanBeInvitedForChatPatch();

                $this->CanBeInvitedForChat = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->Permissions !== null) {
            $innerSize = $this->Permissions->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->Position !== null) {
            $innerSize = $this->Position->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->CanBeInvitedForChat !== null) {
            $innerSize = $this->CanBeInvitedForChat->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->Permissions = null;
        $this->Position = null;
        $this->CanBeInvitedForChat = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AgentSIB\Diadoc\Api\Proto\Employees\EmployeeToUpdate) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->Permissions = ($message->Permissions !== null) ? $message->Permissions : $this->Permissions;
        $this->Position = ($message->Position !== null) ? $message->Position : $this->Position;
        $this->CanBeInvitedForChat = ($message->CanBeInvitedForChat !== null) ? $message->CanBeInvitedForChat : $this->CanBeInvitedForChat;
    }


}

