<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : SignatureVerificationResult.proto
 */


namespace AgentSIB\Diadoc\Api\Proto;

/**
 * Protobuf message : AgentSIB.Diadoc.Api.Proto.CertificateChainElement
 */
class CertificateChainElement extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * CertificateChainStatusFlags required int32 = 1
     *
     * @var int
     */
    protected $CertificateChainStatusFlags = null;

    /**
     * DerCertificate required bytes = 2
     *
     * @var \Protobuf\Stream
     */
    protected $DerCertificate = null;

    /**
     * Check if 'CertificateChainStatusFlags' has a value
     *
     * @return bool
     */
    public function hasCertificateChainStatusFlags()
    {
        return $this->CertificateChainStatusFlags !== null;
    }

    /**
     * Get 'CertificateChainStatusFlags' value
     *
     * @return int
     */
    public function getCertificateChainStatusFlags()
    {
        return $this->CertificateChainStatusFlags;
    }

    /**
     * Set 'CertificateChainStatusFlags' value
     *
     * @param int $value
     */
    public function setCertificateChainStatusFlags($value)
    {
        $this->CertificateChainStatusFlags = $value;
    }

    /**
     * Check if 'DerCertificate' has a value
     *
     * @return bool
     */
    public function hasDerCertificate()
    {
        return $this->DerCertificate !== null;
    }

    /**
     * Get 'DerCertificate' value
     *
     * @return \Protobuf\Stream
     */
    public function getDerCertificate()
    {
        return $this->DerCertificate;
    }

    /**
     * Set 'DerCertificate' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setDerCertificate($value)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->DerCertificate = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['CertificateChainStatusFlags'])) {
            throw new \InvalidArgumentException('Field "CertificateChainStatusFlags" (tag 1) is required but has no value.');
        }

        if ( ! isset($values['DerCertificate'])) {
            throw new \InvalidArgumentException('Field "DerCertificate" (tag 2) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
        ], $values);

        $message->setCertificateChainStatusFlags($values['CertificateChainStatusFlags']);
        $message->setDerCertificate($values['DerCertificate']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CertificateChainElement',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'CertificateChainStatusFlags',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'DerCertificate',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->CertificateChainStatusFlags === null) {
            throw new \UnexpectedValueException('Field "\\AgentSIB\\Diadoc\\Api\\Proto\\CertificateChainElement#CertificateChainStatusFlags" (tag 1) is required but has no value.');
        }

        if ($this->DerCertificate === null) {
            throw new \UnexpectedValueException('Field "\\AgentSIB\\Diadoc\\Api\\Proto\\CertificateChainElement#DerCertificate" (tag 2) is required but has no value.');
        }

        if ($this->CertificateChainStatusFlags !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->CertificateChainStatusFlags);
        }

        if ($this->DerCertificate !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeByteStream($stream, $this->DerCertificate);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->CertificateChainStatusFlags = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->DerCertificate = $reader->readByteStream($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->CertificateChainStatusFlags !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->CertificateChainStatusFlags);
        }

        if ($this->DerCertificate !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->DerCertificate);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->CertificateChainStatusFlags = null;
        $this->DerCertificate = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AgentSIB\Diadoc\Api\Proto\CertificateChainElement) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->CertificateChainStatusFlags = ($message->CertificateChainStatusFlags !== null) ? $message->CertificateChainStatusFlags : $this->CertificateChainStatusFlags;
        $this->DerCertificate = ($message->DerCertificate !== null) ? $message->DerCertificate : $this->DerCertificate;
    }


}

