<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : SignatureVerificationResult.proto
 */


namespace AgentSIB\Diadoc\Api\Proto;

/**
 * Protobuf message : AgentSIB.Diadoc.Api.Proto.CertificateVerificationResult
 */
class CertificateVerificationResult extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * IsValid required bool = 2
     *
     * @var bool
     */
    protected $IsValid = null;

    /**
     * CertificateChain repeated message = 3
     *
     * @var \Protobuf\Collection<\AgentSIB\Diadoc\Api\Proto\CertificateChainElement>
     */
    protected $CertificateChain = null;

    /**
     * VerificationTime required message = 4
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Timestamp
     */
    protected $VerificationTime = null;

    /**
     * Check if 'IsValid' has a value
     *
     * @return bool
     */
    public function hasIsValid()
    {
        return $this->IsValid !== null;
    }

    /**
     * Get 'IsValid' value
     *
     * @return bool
     */
    public function getIsValid()
    {
        return $this->IsValid;
    }

    /**
     * Set 'IsValid' value
     *
     * @param bool $value
     */
    public function setIsValid($value)
    {
        $this->IsValid = $value;
    }

    /**
     * Check if 'CertificateChain' has a value
     *
     * @return bool
     */
    public function hasCertificateChainList()
    {
        return $this->CertificateChain !== null;
    }

    /**
     * Get 'CertificateChain' value
     *
     * @return \Protobuf\Collection<\AgentSIB\Diadoc\Api\Proto\CertificateChainElement>
     */
    public function getCertificateChainList()
    {
        return $this->CertificateChain;
    }

    /**
     * Set 'CertificateChain' value
     *
     * @param \Protobuf\Collection<\AgentSIB\Diadoc\Api\Proto\CertificateChainElement> $value
     */
    public function setCertificateChainList(\Protobuf\Collection $value = null)
    {
        $this->CertificateChain = $value;
    }

    /**
     * Add a new element to 'CertificateChain'
     *
     * @param \AgentSIB\Diadoc\Api\Proto\CertificateChainElement $value
     */
    public function addCertificateChain(\AgentSIB\Diadoc\Api\Proto\CertificateChainElement $value)
    {
        if ($this->CertificateChain === null) {
            $this->CertificateChain = new \Protobuf\MessageCollection();
        }

        $this->CertificateChain->add($value);
    }

    /**
     * Check if 'VerificationTime' has a value
     *
     * @return bool
     */
    public function hasVerificationTime()
    {
        return $this->VerificationTime !== null;
    }

    /**
     * Get 'VerificationTime' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Timestamp
     */
    public function getVerificationTime()
    {
        return $this->VerificationTime;
    }

    /**
     * Set 'VerificationTime' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Timestamp $value
     */
    public function setVerificationTime(\AgentSIB\Diadoc\Api\Proto\Timestamp $value)
    {
        $this->VerificationTime = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['IsValid'])) {
            throw new \InvalidArgumentException('Field "IsValid" (tag 2) is required but has no value.');
        }

        if ( ! isset($values['VerificationTime'])) {
            throw new \InvalidArgumentException('Field "VerificationTime" (tag 4) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'CertificateChain' => [],
        ], $values);

        $message->setIsValid($values['IsValid']);
        $message->setVerificationTime($values['VerificationTime']);

        foreach ($values['CertificateChain'] as $item) {
            $message->addCertificateChain($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CertificateVerificationResult',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'IsValid',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'CertificateChain',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.CertificateChainElement'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'VerificationTime',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Timestamp'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->IsValid === null) {
            throw new \UnexpectedValueException('Field "\\AgentSIB\\Diadoc\\Api\\Proto\\CertificateVerificationResult#IsValid" (tag 2) is required but has no value.');
        }

        if ($this->VerificationTime === null) {
            throw new \UnexpectedValueException('Field "\\AgentSIB\\Diadoc\\Api\\Proto\\CertificateVerificationResult#VerificationTime" (tag 4) is required but has no value.');
        }

        if ($this->IsValid !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeBool($stream, $this->IsValid);
        }

        if ($this->CertificateChain !== null) {
            foreach ($this->CertificateChain as $val) {
                $writer->writeVarint($stream, 26);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->VerificationTime !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeVarint($stream, $this->VerificationTime->serializedSize($sizeContext));
            $this->VerificationTime->writeTo($context);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->IsValid = $reader->readBool($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\CertificateChainElement();

                if ($this->CertificateChain === null) {
                    $this->CertificateChain = new \Protobuf\MessageCollection();
                }

                $this->CertificateChain->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \AgentSIB\Diadoc\Api\Proto\Timestamp();

                $this->VerificationTime = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->IsValid !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->CertificateChain !== null) {
            foreach ($this->CertificateChain as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->VerificationTime !== null) {
            $innerSize = $this->VerificationTime->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->IsValid = null;
        $this->CertificateChain = null;
        $this->VerificationTime = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AgentSIB\Diadoc\Api\Proto\CertificateVerificationResult) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->IsValid = ($message->IsValid !== null) ? $message->IsValid : $this->IsValid;
        $this->CertificateChain = ($message->CertificateChain !== null) ? $message->CertificateChain : $this->CertificateChain;
        $this->VerificationTime = ($message->VerificationTime !== null) ? $message->VerificationTime : $this->VerificationTime;
    }


}

